const token = {
    holo_pro: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2NhZDk5YjJjYjIwNTY2MzhhZWQyNiIsImV4cCI6MTcyMjkxNTM3OSwiaWF0IjoxNzE3NzMxMzc5fQ.kgoeXbczpvcN5CuvjOhTORgHbzEbseVtUFaEsoZZBAY',
    holo_dev: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDM0MDllYjJjYjIwNTY2M2JhMTA4NSIsImV4cCI6MTcyMjkxNTI5MywiaWF0IjoxNzE3NzMxMjkzfQ.xddmBJriZkfxNq5olihbgn5sgkWtrsOhabiDoxyM118',
};

export default token;